name: Update GitHub Stats in README

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch GitHub Stats and Update README
        run: |
          echo "## GitHub Stats" > temp.md
          echo "![GitHub Stats](https://github-readme-stats.vercel.app/api?username=ibrahim89&show_icons=true&count_private=true)" >> temp.md
          cat README.md >> temp.md
          mv temp.md README.md

      - name: Commit and Push Changes
        env:
          GH_STATS_PAT: ${{ secrets.GH_STATS_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Updated GitHub stats" || echo "No changes to commit"
          git push https://x-access-token:${GH_STATS_PAT}@github.com/ibrahim89/YOUR_REPO_NAME.git
